HW10 is complete
taksenov/otus_go pull request #11
Opened 2022-12-18 10:00 UTC by taksenov

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-12-18 10:44 UTC, taksenov commented
Результат Benchmarck:

```
goos: darwin
goarch: arm64
pkg: github.com/taksenov/hw10_program_optimization
BenchmarkFastFuncs-8   	     314	   3567082 ns/op
PASS
ok  	github.com/taksenov/hw10_program_optimization	3.337s
```

2022-12-18 10:58 UTC, dshemin requested changes

2022-12-18 10:58 UTC, dshemin commented on hw10_program_optimization/go.mod
> +module github.com/taksenov/hw10_program_optimization
Критично:

Пакет не go gettable.

2022-12-18 10:58 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		err := u.UnmarshalJSON(scanner.Bytes())
Важно:

Что случиться если у нас будет более 100_000 пользователей?
Более того, в текущей реализации мы:
1. Сначала проходимся по всем записям и превращем их в структуру.
2. Сохраняем все структуры в памяти.
3. Потом пробегаемся по всем структурам и берём оттуда только email, чтобы посчитать домены.

В итоге - чем больше записей - тем больше памяти мы будем съедать. Можно оптимизировать до константного потребления памяти. И мы делаем дополнительное иттерирование, чего так же можно избежать. Есть ещё что пооптимизировать.

2022-12-18 15:08 UTC, taksenov commented on hw10_program_optimization/go.mod
> +module github.com/taksenov/hw10_program_optimization
Внес коррективы.

2022-12-18 15:10 UTC, taksenov commented on hw10_program_optimization/stats.go
> +		err := u.UnmarshalJSON(scanner.Bytes())
Опирался на ограничение, что нельзя менять сигнатуру функции:
https://github.com/taksenov/otus_go/blob/168a86edbd3c2431a6e0d4a13a0568667eb03e2b/hw10_program_optimization/README.md?plain=1#L25

Более оптимизированное решение, которое рекомендовано реализовать и представлено сейчас, все же частично нарушает это условие.

2022-12-18 15:22 UTC, taksenov commented
Мегабайт удалось сэкономить, судя по тестам, убрав перекладывание количества доменов (`num`)

**Было:**

```
=== RUN   TestGetDomainStat_Time_And_Memory
    stats_optimization_test.go:46: time used: 125.857ms / 300ms
    stats_optimization_test.go:47: memory used: 11Mb / 30Mb
--- PASS: TestGetDomainStat_Time_And_Memory (1.44s)
PASS
ok  	github.com/taksenov/hw10programoptimization	2.109s
```

**Стало:**

```
=== RUN   TestGetDomainStat_Time_And_Memory
    stats_optimization_test.go:46: time used: 124.854375ms / 300ms
    stats_optimization_test.go:47: memory used: 10Mb / 30Mb
--- PASS: TestGetDomainStat_Time_And_Memory (1.42s)
PASS
ok  	github.com/taksenov/hw10programoptimization	1.695s
```

2022-12-18 15:35 UTC, taksenov commented on hw10_program_optimization/stats.go
> +		err := u.UnmarshalJSON(scanner.Bytes())
Внес коррективы.

2022-12-18 15:39 UTC, taksenov commented
Обновленный бенчмарк:

```
goos: darwin
goarch: arm64
pkg: github.com/taksenov/hw10programoptimization
BenchmarkFastFuncs-8   	 2538692	       450.0 ns/op
PASS
ok  	github.com/taksenov/hw10programoptimization	3.393s
```

2022-12-18 15:51 UTC, dshemin requested changes

2022-12-18 15:51 UTC, dshemin commented on hw10_program_optimization/go.mod
> +module github.com/taksenov/hw10programoptimization
Критично:

Вместо `fixme_my_friend` должно быть полное название репозитория `taksenov/otus_go`. Плюс - верните название пакета `hw10_programm_optimization` как был.

Пожалуйста, освежите в памяти как работает `go get`.

2022-12-18 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		err := u.UnmarshalJSON(scanner.Bytes())
При предложенным мной способе оптимизации сигнатура (Имя, аргументы, их порядок и типы, а также возвращаемые значения, их порядок и типы не меняется).

2022-12-18 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +			d := strings.ToLower(strings.SplitN(u.Email, "@", 2)[1])
Важно:

Стоит привести строку к нижнему регистру до поиска вхождения домена. Текущий код в email `user@example.COM` не найдёт домен `com`.

2022-12-18 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		// NB: `get users error` -- вывод ошибки становится бессмысленным.
Совет:

Текст ошибки - не часть сигнатуры. Вот если бы это была константная ошибка или специальный тип ошибки и вы поменяли - тогда да. Она бы сломала код. Полагаться на текст ошибки - последнее что стоит делать.

2022-12-19 13:47 UTC, taksenov commented on hw10_program_optimization/stats.go
> +		err := u.UnmarshalJSON(scanner.Bytes())
Согласен.

Внес коррективы.

2022-12-19 13:47 UTC, taksenov commented on hw10_program_optimization/go.mod
> +module github.com/taksenov/hw10programoptimization
Освежил. Спасибо.

2022-12-19 13:48 UTC, taksenov commented on hw10_program_optimization/stats.go
> +			d := strings.ToLower(strings.SplitN(u.Email, "@", 2)[1])
Внес коррективы.

Универсальность добавила накладных расходов на 3 MB

Потребление памяти увеличилось с 10Mib до 13Mib

```
=== RUN   TestGetDomainStat_Time_And_Memory
    stats_optimization_test.go:46: time used: 131.586958ms / 300ms
    stats_optimization_test.go:47: memory used: 13Mb / 30Mb
--- PASS: TestGetDomainStat_Time_And_Memory (1.50s)
PASS
ok  	github.com/taksenov/otus_go/hw10_program_optimization	1.859s
```

2022-12-19 13:49 UTC, taksenov commented on hw10_program_optimization/stats.go
> +		// NB: `get users error` -- вывод ошибки становится бессмысленным.
Понял, принял. Спасибо.

2022-12-19 14:38 UTC, dshemin approved these changes

2022-12-19 16:58 UTC, merged