HW11 is complete
taksenov/otus_go pull request #13
Opened 2023-01-16 11:13 UTC by taksenov

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2023-01-16 19:52 UTC, gna69 requested changes
Сам код прост и хорошо читается, в нем отсутсвуют громосткие конструкции и большие вложенности кода. Это отлично!

Предлагаю доработать его в соответсвием с моими рекомендациями.

Хорошо, что написаны тесты. Работа выполнена на 6 баллов.

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/main.go
> +					log.Fatal(err)
log.Fatal под капотом вызывает функцию os.Exit, которая немедленно завершает приложение
Это значит, что при ошибке код на 62 строчке и ниже не выполнится никогда
При этом defer так же не будет выполнен

Предлагаю использовать для логирования ошибок log.Println или подключить пакет, позволяющий логировать по уровням и залогировать ошибки в уровень Error(например, zerolog'ом)

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/main.go
> +					log.Fatal(err)
Аналогично, код ниже и defer не выполнятся

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/telnet.go
> +		return
В данном случае если это условие выполняется, то метод send вернет nil, вместо ошибки, хотя попытка отправить данные при несуществующем коннекте должна заканчиваться ошибкой

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/telnet.go
> +		return errors.New("end")
Для обозначения того, что операция достигла конца ввода-вывода в стандартном пакете ввода вывода есть ошибка EOF, предлагаю использовать ее

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/telnet.go
> +	return
В бест пректиксах по написанию чистого понятного кода есть правило "явное лучше неявного", в данном случае его можно применить так: если функция возвращает ошибку, лучше явно сделать это на каждом return. В случае, если все прошло без ошибок, можно вернуть nil

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/telnet.go
> +func (t *clientAbstraction) Receive() (err error) {
Аналогично ф-ии Send

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/main.go
> +	ctx, cancel := context.WithCancel(context.Background())
В го принято код по освобождению/закрытию ресурсов писать как можно ближе к месту их выделения с использованием defer, предлагаю применить этот подход и тут

2023-01-16 19:52 UTC, gna69 commented on hw11_telnet_client/main.go
> +		os.Exit(1)
Если в момент прерывания SIGINT или SIGTERM рутина отправляла данные в сокет, то она будет принудительно завершена, так как os.Exit закрывает программу немедленно 
Graceful Shutdown в свою очедерь позволяет завершить все процессы приложения аккуратно

Предлагаю вместо os.Exit сообщить другим рутинам через контекст о том, что нужно завершиться

2023-01-17 09:53 UTC, taksenov commented on hw11_telnet_client/telnet.go
> +	return err
Внес коррективы.

2023-01-17 09:55 UTC, taksenov commented on hw11_telnet_client/telnet.go
> +	return t.conn.Close()
Внес коррективы.

2023-01-17 09:57 UTC, taksenov commented on hw11_telnet_client/main.go
> +					log.Fatal(err)
Внес коррективы.

2023-01-17 09:57 UTC, taksenov commented on hw11_telnet_client/main.go
> +					log.Fatal(err)
Внес коррективы.

2023-01-17 10:25 UTC, taksenov commented on hw11_telnet_client/telnet.go
> +		return errors.New("end")
Внес коррективы.

2023-01-17 10:29 UTC, taksenov commented on hw11_telnet_client/telnet.go
> +	return
Внес коррективы.

2023-01-17 10:29 UTC, taksenov commented on hw11_telnet_client/telnet.go
> +func (t *clientAbstraction) Receive() (err error) {
Внес коррективы.

2023-01-17 10:37 UTC, taksenov commented on hw11_telnet_client/main.go
> +	ctx, cancel := context.WithCancel(context.Background())
Внес коррективы.

2023-01-17 10:37 UTC, taksenov commented on hw11_telnet_client/main.go
> +		os.Exit(1)
Внес коррективы.

2023-01-17 11:58 UTC, gna69 approved these changes
Код прост для чтения, корректен, не содержит больших вложенностей.

В файле main.go на строке 43 создается канал, однако он нигде не закрывается. В текущей программе после ее завершения все ресурсы вернутся к ОС, однако если бы это был промежуточный код (например создавался канал для получения ответа от какого-то сервиса в асинхронном режиме), то это бы привело к утечке памяти: выделению ресурсов и не освобождению их, когда они больше не нужны. Рекомендую приучиться освобождать выделенные ресурсы с помощью defer.

Работа выполнена полностью. Оцениваю в 10 баллов.

2023-01-17 14:13 UTC, merged